// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://babtwecvfqiojqobdpdz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJhYnR3ZWN2ZnFpb2pxb2JkcGR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNzQzMzMsImV4cCI6MjA2MDc1MDMzM30.mHVbXBd73O-bVb3nbWrp0xa_43oiqY9y7tyjE5klNMQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);